#!/usr/bin/env python3
"""
License: BSD 3-Clause

CLI for comparing PNW-Cnet model predictions on sox vs sox_tensorflow spectrograms.

Reads matched ``.sox.png`` / ``.tf.png`` spectrogram pairs from a directory
(generated by ``compare_spectrograms_cli.py``) and writes results to CSV for
analysis in the accompanying notebook (``analysis.ipynb``).

Usage examples::

    # Basic run (spectrograms already generated by compare_spectrograms_cli)
    python model_comparison_cli.py \\
        --model ../../../pnw/PNW-Cnet_v4_TF.h5 \\
        --classes ../../../pnw/target_classes.csv

    # Custom spectrogram and output directories
    python model_comparison_cli.py \\
        --model /path/to/PNW-Cnet_v4_TF.h5 \\
        --classes /path/to/target_classes.csv \\
        --spectrograms my_run/spectrograms \\
        --output my_run/results
"""

import csv
import os
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import click
import numpy as np
import tensorflow as tf
from PIL import Image

# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

def load_pnw_model(model_path: Path) -> tf.keras.Model:
    """Load the PNW-Cnet model from an HDF5 file.

    First attempts a direct ``load_model`` call; falls back to manual
    architecture reconstruction with weight loading if that fails (e.g. due
    to Keras version differences).

    Args:
        model_path: Path to ``PNW-Cnet_v4_TF.h5``.

    Returns:
        Loaded and verified Keras model.

    Raises:
        RuntimeError: If the model cannot be loaded by either strategy.
    """
    click.echo("Loading PNW-Cnet model...")

    try:
        model = tf.keras.models.load_model(str(model_path))
        click.echo("  Loaded directly.")
        return model
    except Exception as exc:
        click.echo(f"  Direct load failed ({exc}), attempting manual reconstruction...")

    # Manual reconstruction matching PNW-Cnet v4 architecture
    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(32, (5, 5), activation="relu", padding="same",
                               input_shape=(257, 1000, 1), name="conv2d_1"),
        tf.keras.layers.MaxPooling2D((2, 2), name="max_pooling2d_1"),
        tf.keras.layers.Dropout(0.25, name="dropout_1"),

        tf.keras.layers.Conv2D(32, (5, 5), activation="relu", padding="same", name="conv2d_2"),
        tf.keras.layers.MaxPooling2D((2, 2), name="max_pooling2d_2"),
        tf.keras.layers.Dropout(0.25, name="dropout_2"),

        tf.keras.layers.Conv2D(64, (5, 5), activation="relu", padding="same", name="conv2d_3"),
        tf.keras.layers.MaxPooling2D((2, 2), name="max_pooling2d_3"),
        tf.keras.layers.Dropout(0.25, name="dropout_3"),

        tf.keras.layers.Conv2D(64, (5, 5), activation="relu", padding="same", name="conv2d_4"),
        tf.keras.layers.MaxPooling2D((2, 2), name="max_pooling2d_4"),
        tf.keras.layers.Dropout(0.25, name="dropout_4"),

        tf.keras.layers.Conv2D(128, (5, 5), activation="relu", padding="same", name="conv2d_5"),
        tf.keras.layers.MaxPooling2D((2, 2), name="max_pooling2d_5"),
        tf.keras.layers.Dropout(0.25, name="dropout_5"),

        tf.keras.layers.Conv2D(128, (5, 5), activation="relu", padding="same", name="conv2d_6"),
        tf.keras.layers.MaxPooling2D((2, 2), name="max_pooling2d_6"),
        tf.keras.layers.Dropout(0.25, name="dropout_6"),

        tf.keras.layers.Flatten(name="flatten_1"),
        tf.keras.layers.Dropout(0.5, name="dropout_7"),

        tf.keras.layers.Dense(256, activation="relu", name="dense_1"),
        tf.keras.layers.Dropout(0.5, name="dropout_8"),

        tf.keras.layers.Dense(51, activation="softmax", name="dense_2"),
    ])

    # Warm up the graph before weight loading
    _ = model(np.zeros((1, 257, 1000, 1), dtype=np.float32), training=False)

    try:
        model.load_weights(str(model_path), by_name=True)
        click.echo("  Reconstructed and weights loaded.")
        return model
    except Exception as exc:
        raise RuntimeError(f"Could not load PNW-Cnet model: {exc}") from exc


# ---------------------------------------------------------------------------
# Class map
# ---------------------------------------------------------------------------

def load_target_classes(csv_path: Path) -> Dict[int, str]:
    """Load the class-index-to-name mapping from a CSV file.

    The CSV must have a ``Class`` column; rows are indexed by their order.

    Args:
        csv_path: Path to ``target_classes.csv``.

    Returns:
        Dict mapping ``int`` index → class name string.
    """
    class_map: Dict[int, str] = {}
    with open(csv_path, "r") as f:
        for i, row in enumerate(csv.DictReader(f)):
            class_map[i] = row["Class"]
    return class_map


# ---------------------------------------------------------------------------
# Spectrogram loading
# ---------------------------------------------------------------------------

def load_spectrogram_for_model(png_path: Path) -> np.ndarray:
    """Load a spectrogram PNG and return a model-ready float32 array.

    Args:
        png_path: Path to the PNG file (palette, greyscale, or RGB).

    Returns:
        Float32 array with shape ``(1, 257, 1000, 1)`` and values in ``[0, 1]``.
    """
    img = Image.open(png_path)
    if img.mode in ("P", "RGB"):
        img = img.convert("L")
    arr = np.array(img, dtype=np.float32) / 255.0
    return arr[np.newaxis, :, :, np.newaxis]  # (1, H, W, 1)


# ---------------------------------------------------------------------------
# Prediction comparison
# ---------------------------------------------------------------------------

def _top_n_classes(probs: np.ndarray, class_map: Dict[int, str], n: int = 5) -> List[str]:
    """Return the top-n class names sorted by probability descending."""
    return [class_map[i] for i in np.argsort(probs)[::-1][:n]]


def _high_confidence_analysis(
    ref_probs: np.ndarray,
    cmp_probs: np.ndarray,
    class_map: Dict[int, str],
    threshold: float = 0.1,
) -> Dict:
    """Summarise prediction differences for classes where ref_probs ≥ threshold.

    Args:
        ref_probs: Reference class probabilities (length = n_classes).
        cmp_probs: Comparison class probabilities.
        class_map: Class index → name.
        threshold: Minimum probability in the reference prediction.

    Returns:
        Dict with keys: ``n_classes``, ``total_diff``, ``max_diff``, ``avg_diff``.
    """
    idx = np.where(ref_probs >= threshold)[0]
    if len(idx) == 0:
        return {"n_classes": 0, "total_diff": 0.0, "max_diff": 0.0, "avg_diff": 0.0}

    diffs = np.abs(ref_probs[idx] - cmp_probs[idx])
    return {
        "n_classes": len(idx),
        "total_diff": float(np.sum(diffs)),
        "max_diff": float(np.max(diffs)),
        "avg_diff": float(np.mean(diffs)),
    }


def compare_pair(
    model: tf.keras.Model,
    sox_path: Path,
    tf_path: Path,
    class_map: Dict[int, str],
) -> Tuple[Dict, List[Dict]]:
    """Run the model on one spectrogram pair and return comparison metrics.

    Args:
        model: Loaded Keras model.
        sox_path: Path to the ``.sox.png`` spectrogram.
        tf_path: Path to the ``.tf.png`` spectrogram.
        class_map: Class index → name.

    Returns:
        Tuple of:
        - summary dict: per-pair metrics (top-1 agreement, vector differences,
          high-confidence analysis)
        - class_diffs list: one row per class with sox_prob, tf_prob, and diff
    """
    sox_input = load_spectrogram_for_model(sox_path)
    tf_input = load_spectrogram_for_model(tf_path)

    # Use direct call (avoids per-call graph retracing on Metal/GPU)
    sox_probs: np.ndarray = model(sox_input, training=False).numpy()[0]
    tf_probs: np.ndarray = model(tf_input, training=False).numpy()[0]

    sox_top5 = _top_n_classes(sox_probs, class_map, n=5)
    tf_top5 = _top_n_classes(tf_probs, class_map, n=5)

    pred_diff = np.abs(sox_probs - tf_probs)

    sox_hc = _high_confidence_analysis(sox_probs, tf_probs, class_map)
    tf_hc = _high_confidence_analysis(tf_probs, sox_probs, class_map)

    # Derive segment metadata from filename e.g. "20230522_000000-12.sox.png"
    stem = sox_path.name.replace(".sox.png", "")
    parts = stem.rsplit("-", 1)
    audio_file = parts[0] if len(parts) == 2 else stem
    segment_idx = int(parts[1]) if len(parts) == 2 and parts[1].isdigit() else -1

    summary = {
        "audio_file": audio_file,
        "segment_idx": segment_idx,
        "sox_top_class": sox_top5[0],
        "tf_top_class": tf_top5[0],
        "sox_top_prob": float(sox_probs[np.argmax(sox_probs)]),
        "tf_top_prob": float(tf_probs[np.argmax(tf_probs)]),
        "same_top_prediction": sox_top5[0] == tf_top5[0],
        "prob_diff_top": float(abs(float(sox_probs[np.argmax(sox_probs)]) - float(tf_probs[np.argmax(tf_probs)]))),
        "max_vector_diff": float(np.max(pred_diff)),
        "mean_vector_diff": float(np.mean(pred_diff)),
        "sox_hc_classes": sox_hc["n_classes"],
        "sox_hc_total_diff": sox_hc["total_diff"],
        "sox_hc_max_diff": sox_hc["max_diff"],
        "sox_hc_avg_diff": sox_hc["avg_diff"],
        "tf_hc_classes": tf_hc["n_classes"],
        "tf_hc_total_diff": tf_hc["total_diff"],
        "tf_hc_max_diff": tf_hc["max_diff"],
        "tf_hc_avg_diff": tf_hc["avg_diff"],
    }

    class_diffs = [
        {
            "audio_file": audio_file,
            "segment_idx": segment_idx,
            "class_code": class_map[i],
            "sox_prob": float(sox_probs[i]),
            "tf_prob": float(tf_probs[i]),
            "diff": float(sox_probs[i] - tf_probs[i]),
            "abs_diff": float(pred_diff[i]),
        }
        for i in range(len(sox_probs))
    ]

    return summary, class_diffs


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).parent
_DEFAULT_MODEL   = _SCRIPT_DIR / "pnw" / "PNW-Cnet_v4_TF.h5"
_DEFAULT_CLASSES = _SCRIPT_DIR / "pnw" / "target_classes.csv"


@click.command(context_settings={"help_option_names": ["-h", "--help"]})
@click.option(
    "--model", "-m",
    default=str(_DEFAULT_MODEL),
    show_default=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to PNW-Cnet_v4_TF.h5 model file.",
)
@click.option(
    "--classes", "-c",
    default=str(_DEFAULT_CLASSES),
    show_default=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to target_classes.csv.",
)
@click.option(
    "--spectrograms", "-s",
    default=None,
    type=click.Path(file_okay=False),
    help="Directory containing .sox.png / .tf.png pairs "
         "[default: <script_dir>/spectrograms]",
)
@click.option(
    "--output", "-o",
    default=None,
    type=click.Path(),
    help="Output directory for results [default: <script_dir>/results]",
)
def main(
    model: str,
    classes: str,
    spectrograms: Optional[str],
    output: Optional[str],
) -> None:
    """Compare PNW-Cnet predictions on sox vs sox_tensorflow spectrogram pairs.

    Reads matched .sox.png / .tf.png files from the SPECTROGRAMS directory
    (default: ./spectrograms, produced by compare_spectrograms_cli.py).
    """
    spectrograms_dir = Path(spectrograms) if spectrograms else _SCRIPT_DIR / "spectrograms"
    results_dir = Path(output) if output else _SCRIPT_DIR / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    if not spectrograms_dir.is_dir():
        raise click.ClickException(f"Spectrograms directory not found: {spectrograms_dir}")

    # Load model and class map
    try:
        tf_model = load_pnw_model(Path(model))
        # Warm-up inference pass
        _ = tf_model(np.zeros((1, 257, 1000, 1), dtype=np.float32), training=False)
        click.echo(f"  Output shape: {_.shape}")
    except Exception as exc:
        raise click.ClickException(f"Failed to load model: {exc}") from exc

    class_map = load_target_classes(Path(classes))
    click.echo(f"Loaded {len(class_map)} classes.")

    # Find matched spectrogram pairs
    sox_files = sorted(spectrograms_dir.glob("*.sox.png"))
    pairs: List[Tuple[Path, Path]] = []
    for sox_f in sox_files:
        tf_f = spectrograms_dir / sox_f.name.replace(".sox.png", ".tf.png")
        if tf_f.exists():
            pairs.append((sox_f, tf_f))
        else:
            click.echo(f"  Warning: no matching .tf.png for {sox_f.name}", err=True)

    click.echo(f"Found {len(pairs)} matched spectrogram pairs.")
    if not pairs:
        raise click.ClickException("No matched pairs found — run compare_spectrograms_cli.py first.")

    # Run comparisons
    results: List[Dict] = []
    all_class_diffs: List[Dict] = []
    for i, (sox_f, tf_f) in enumerate(pairs):
        click.echo(f"  [{i + 1:4d}/{len(pairs)}] {sox_f.name}", nl=False)
        try:
            summary, class_diffs = compare_pair(tf_model, sox_f, tf_f, class_map)
            results.append(summary)
            all_class_diffs.extend(class_diffs)
            match = "✓" if summary["same_top_prediction"] else "✗"
            click.echo(f"  {match} sox={summary['sox_top_class']} tf={summary['tf_top_class']}")
        except Exception as exc:
            click.echo(f"  ERROR: {exc}", err=True)

    if not results:
        raise click.ClickException("No results generated.")

    # Write summary CSV
    csv_path = results_dir / "model_comparison.csv"
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(results[0].keys()))
        writer.writeheader()
        writer.writerows(results)

    # Write per-class probability diff CSV
    class_csv_path = results_dir / "model_class_diffs.csv"
    with open(class_csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(all_class_diffs[0].keys()))
        writer.writeheader()
        writer.writerows(all_class_diffs)
    click.echo(f"Per-class diffs written to {class_csv_path}")

    # Terminal summary
    n = len(results)
    agree = sum(1 for r in results if r["same_top_prediction"])
    click.echo(f"\n{'=' * 50}")
    click.echo("Model Comparison Results")
    click.echo(f"{'=' * 50}")
    click.echo(f"  Pairs analysed     : {n}")
    click.echo(f"  Top-1 agreement    : {agree}/{n} ({agree / n * 100:.2f}%)")
    click.echo(f"  Avg prob diff      : {np.mean([r['prob_diff_top'] for r in results]):.6f}")
    click.echo(f"  Max prob diff      : {np.max([r['prob_diff_top'] for r in results]):.6f}")
    click.echo(f"  Avg vec diff       : {np.mean([r['mean_vector_diff'] for r in results]):.6f}")
    click.echo(f"\nResults saved to {results_dir}")


if __name__ == "__main__":
    main()
