#!/usr/bin/env python3
"""
License: BSD 3-Clause

CLI for comparing spectrograms generated by the sox binary vs sox_tensorflow.

Generates N random 12-second segments per audio file, creates spectrogram pairs,
and writes results to CSV files for analysis in the accompanying notebook
(``analysis.ipynb``).

Usage examples::

    # Single file
    python compare_spectrograms_cli.py audio/20230522_000000.flac

    # Multiple files
    python compare_spectrograms_cli.py audio/file1.flac audio/file2.flac

    # Directory of audio files
    python compare_spectrograms_cli.py audio/

    # S3 URI (single file or prefix)
    python compare_spectrograms_cli.py s3://my-bucket/audio/20230522_000000.flac
    python compare_spectrograms_cli.py s3://my-bucket/audio/

    # Custom output
    python compare_spectrograms_cli.py audio/ --output my_run --n-samples 20
"""

import csv
import random
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from urllib.parse import urlparse

import click
import numpy as np
import soundfile as sf
import yaml
from PIL import Image

from sox_tensorflow.processor import spectrogram_from_flac

# ---------------------------------------------------------------------------
# Audio file resolution (local paths + S3 URIs)
# ---------------------------------------------------------------------------

AUDIO_EXTENSIONS = {".flac", ".wav", ".mp3", ".ogg"}


def _s3_download(boto3, bucket: str, key: str, dest: str) -> None:
    """Download an S3 object, falling back to anonymous access on 4xx errors."""
    from botocore import UNSIGNED
    from botocore.config import Config
    from botocore.exceptions import ClientError

    try:
        boto3.client("s3").download_file(bucket, key, dest)
    except ClientError as exc:
        status = exc.response.get("ResponseMetadata", {}).get("HTTPStatusCode", 0)
        if 400 <= status < 500:
            boto3.client("s3", config=Config(signature_version=UNSIGNED)).download_file(bucket, key, dest)
        else:
            raise


def _resolve_s3_path(uri: str, tmp_dir: Path) -> List[Path]:
    """Download files from an S3 URI to a local temp directory.

    Args:
        uri: S3 URI — either a single file (``s3://bucket/key.flac``) or a
            prefix (``s3://bucket/prefix/``).
        tmp_dir: Local directory to download files into.

    Returns:
        List of local paths to the downloaded files.
    """
    try:
        import boto3
    except ImportError as exc:
        raise RuntimeError("boto3 is required for S3 support: pip install boto3") from exc

    parsed = urlparse(uri)
    bucket = parsed.netloc
    key = parsed.path.lstrip("/")

    from botocore import UNSIGNED
    from botocore.config import Config
    from botocore.exceptions import ClientError

    def _make_client():
        return boto3.client("s3")

    def _make_anon_client():
        return boto3.client("s3", config=Config(signature_version=UNSIGNED))

    def _list_objects(prefix):
        """List objects, falling back to anonymous on 4xx."""
        try:
            paginator = _make_client().get_paginator("list_objects_v2")
            pages = list(paginator.paginate(Bucket=bucket, Prefix=prefix))
        except ClientError as exc:
            status = exc.response.get("ResponseMetadata", {}).get("HTTPStatusCode", 0)
            if 400 <= status < 500:
                paginator = _make_anon_client().get_paginator("list_objects_v2")
                pages = list(paginator.paginate(Bucket=bucket, Prefix=prefix))
            else:
                raise
        return pages

    # If the key ends with "/" or has no extension treat as a prefix
    if uri.endswith("/") or not Path(key).suffix:
        local_paths: List[Path] = []
        for page in _list_objects(key):
            for obj in page.get("Contents", []):
                obj_key = obj["Key"]
                if Path(obj_key).suffix.lower() in AUDIO_EXTENSIONS:
                    dest = tmp_dir / Path(obj_key).name
                    click.echo(f"  Downloading s3://{bucket}/{obj_key} → {dest}")
                    _s3_download(boto3, bucket, obj_key, str(dest))
                    local_paths.append(dest)
        return local_paths

    # Single file
    dest = tmp_dir / Path(key).name
    click.echo(f"Downloading s3://{bucket}/{key} → {dest}")
    _s3_download(boto3, bucket, key, str(dest))
    return [dest]


def resolve_audio_inputs(inputs: Tuple[str, ...]) -> List[Path]:
    """Resolve a mix of local paths, directories, and S3 URIs to local file paths.

    Downloads S3 files to a shared temp directory that is returned alongside
    the paths so callers can keep the directory alive for the duration of the run.

    Args:
        inputs: Tuple of path strings or S3 URIs supplied on the CLI.

    Returns:
        Sorted list of resolved local audio file paths.

    Raises:
        click.ClickException: If a path does not exist or no audio files are found.
    """
    tmp_dir = Path(tempfile.mkdtemp(prefix="sox_cmp_"))
    resolved: List[Path] = []

    for inp in inputs:
        if inp.startswith("s3://"):
            resolved.extend(_resolve_s3_path(inp, tmp_dir))
            continue

        p = Path(inp)
        if not p.exists():
            raise click.ClickException(f"Path not found: {p}")

        if p.is_dir():
            for ext in AUDIO_EXTENSIONS:
                resolved.extend(p.glob(f"*{ext}"))
                resolved.extend(p.glob(f"*{ext.upper()}"))
        elif p.suffix.lower() in AUDIO_EXTENSIONS:
            resolved.append(p)
        else:
            raise click.ClickException(f"Unsupported file type: {p}")

    resolved = sorted(set(resolved))
    if not resolved:
        raise click.ClickException("No audio files found in the supplied inputs.")
    return resolved


# ---------------------------------------------------------------------------
# Spectrogram generation helpers
# ---------------------------------------------------------------------------

def get_audio_duration(flac_path: Path) -> float:
    """Return the duration of an audio file in seconds.

    Args:
        flac_path: Path to the audio file.

    Returns:
        Duration in seconds.
    """
    info = sf.info(str(flac_path))
    return info.frames / info.samplerate


def generate_random_segments(
    audio_duration: float,
    segment_duration: float = 12.0,
    n_samples: int = 50,
) -> List[float]:
    """Return ``n_samples`` random segment start times.

    Args:
        audio_duration: Total duration of the audio file in seconds.
        segment_duration: Length of each segment in seconds.
        n_samples: Number of segments to sample.

    Returns:
        List of start times (seconds).

    Raises:
        ValueError: If the file is too short for the requested segment length.
    """
    max_start = audio_duration - segment_duration
    if max_start <= 0:
        raise ValueError(
            f"Audio file too short ({audio_duration:.1f}s) for {segment_duration}s segments"
        )
    return [random.uniform(0, max_start) for _ in range(n_samples)]


def create_sox_spectrogram(
    audio_path: Path,
    start_time: float,
    duration: float,
    output_path: Path,
) -> None:
    """Generate a spectrogram PNG using the sox binary.

    Parameters match those used by the PNW-Cnet pipeline (pnw/functions.r).

    Args:
        audio_path: Input audio file.
        start_time: Segment start time in seconds.
        duration: Segment length in seconds.
        output_path: Destination PNG file path.

    Raises:
        RuntimeError: If the sox process exits with a non-zero status.
    """
    cmd = [
        "sox", "-V1", str(audio_path), "-n",
        "trim", str(start_time), str(duration),
        "remix", "1",
        "rate", "8k",
        "spectrogram",
        "-x", "1000",
        "-y", "257",
        "-z", "90",
        "-m", "-r",
        "-o", str(output_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"sox failed: {result.stderr.strip()}")


def load_spectrogram_pixels(png_path: Path) -> np.ndarray:
    """Load a spectrogram PNG as a uint8 pixel array.

    Handles both palette-mode (``P``) and greyscale (``L``) images.

    Args:
        png_path: Path to the PNG file.

    Returns:
        2-D uint8 array with shape ``(height, width)``.
    """
    img = Image.open(png_path)
    if img.mode == "P":
        img = img.convert("L")
    return np.array(img, dtype=np.uint8)


# ---------------------------------------------------------------------------
# Pixel statistics
# ---------------------------------------------------------------------------

def compute_pixel_statistics(
    sox_pixels: np.ndarray, tf_pixels: np.ndarray
) -> Dict[str, float]:
    """Compute pixel-level agreement statistics between two spectrogram arrays.

    Args:
        sox_pixels: Reference pixel array from sox.
        tf_pixels: Comparison pixel array from sox_tensorflow.

    Returns:
        Dictionary of scalar statistics.
    """
    assert sox_pixels.shape == tf_pixels.shape, (
        f"Shape mismatch: {sox_pixels.shape} vs {tf_pixels.shape}"
    )
    diff = sox_pixels.astype(np.int16) - tf_pixels.astype(np.int16)
    abs_diff = np.abs(diff)
    total = sox_pixels.size

    stats: Dict[str, float] = {
        "accuracy": float(np.mean(sox_pixels == tf_pixels) * 100),
        "std_dev": float(np.std(diff)),
        "max_diff": float(np.max(abs_diff)),
        "min_diff": float(np.min(abs_diff)),
        "mean_abs_diff": float(np.mean(abs_diff)),
        "pixels_within_1": int(np.sum(abs_diff <= 1)),
        "pixels_within_2": int(np.sum(abs_diff <= 2)),
        "pixels_within_5": int(np.sum(abs_diff <= 5)),
        "pixels_greater_5": int(np.sum(abs_diff > 5)),
        "total_pixels": total,
    }
    stats["pct_within_1"] = (stats["pixels_within_1"] / total) * 100
    stats["pct_within_2"] = (stats["pixels_within_2"] / total) * 100
    stats["pct_within_5"] = (stats["pixels_within_5"] / total) * 100
    stats["pct_greater_5"] = (stats["pixels_greater_5"] / total) * 100
    return stats


def compute_brightness_decile_stats(
    sox_pixels: np.ndarray, tf_pixels: np.ndarray
) -> List[Dict]:
    """Compute agreement statistics broken down by 10% brightness decile.

    Deciles are computed on the sox (reference) pixel distribution, then the
    same pixel positions are compared across both images.

    Args:
        sox_pixels: Reference pixel array from sox.
        tf_pixels: Comparison pixel array from sox_tensorflow.

    Returns:
        List of dicts — one per decile — from darkest (0–10 %) to
        brightest (90–100 %).  Each dict includes the percentile range label,
        brightness thresholds, and all statistics from
        :func:`compute_pixel_statistics`.
    """
    sox_flat = sox_pixels.flatten()
    tf_flat = tf_pixels.flatten()
    decile_stats = []

    for p in range(0, 100, 10):
        p_low = float(np.percentile(sox_flat, p))
        p_high = float(np.percentile(sox_flat, p + 10))

        mask = (sox_flat >= p_low) if p == 90 else (sox_flat >= p_low) & (sox_flat < p_high)
        if not mask.any():
            continue

        stats = compute_pixel_statistics(
            sox_flat[mask].reshape(-1, 1),
            tf_flat[mask].reshape(-1, 1),
        )
        stats["percentile_range"] = f"{p}-{p + 10}%"
        stats["brightness_low"] = p_low
        stats["brightness_high"] = p_high
        decile_stats.append(stats)

    return decile_stats


# ---------------------------------------------------------------------------
# Per-segment comparison
# ---------------------------------------------------------------------------

def compare_segment(
    audio_path: Path,
    start_time: float,
    segment_idx: int,
    base_filename: str,
    spectrograms_dir: Path,
) -> Tuple[Dict, List[Dict]]:
    """Generate and compare spectrogram pairs for one audio segment.

    Args:
        audio_path: Source audio file.
        start_time: Segment start time in seconds.
        segment_idx: Index label used in output filenames.
        base_filename: Stem of the audio file (e.g. ``"20230522_000000"``).
        spectrograms_dir: Directory to write PNG files into.

    Returns:
        Tuple of ``(overall_stats, decile_stats)`` where ``overall_stats``
        includes audio metadata and ``decile_stats`` is a list of per-decile
        dicts.
    """
    duration = 12.0
    sox_png = spectrograms_dir / f"{base_filename}-{segment_idx}.sox.png"
    tf_png = spectrograms_dir / f"{base_filename}-{segment_idx}.tf.png"

    create_sox_spectrogram(audio_path, start_time, duration, sox_png)
    spectrogram_from_flac(
        flac_path=str(audio_path),
        start_time=start_time,
        duration=duration,
        shape=(257, 1000),
        dest=str(tf_png),
        db_range=90,
    )

    sox_pixels = load_spectrogram_pixels(sox_png)
    tf_pixels = load_spectrogram_pixels(tf_png)

    overall = compute_pixel_statistics(sox_pixels, tf_pixels)
    overall["audio_file"] = base_filename
    overall["segment_idx"] = segment_idx
    overall["start_time"] = start_time

    decile = compute_brightness_decile_stats(sox_pixels, tf_pixels)

    return overall, decile


# ---------------------------------------------------------------------------
# Config + CLI entry point
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).parent
_DEFAULT_CONFIG = _SCRIPT_DIR / "config.yaml"


def _apply_config(ctx: click.Context, param: click.Parameter, value: Optional[str]) -> Optional[str]:
    """Load a YAML config file and apply it as click default_map.

    Runs eagerly so that explicit CLI flags always override config values.
    If *value* is ``None`` and ``config.yaml`` exists next to the script,
    that file is used automatically.  The ``audio`` key is skipped here and
    resolved in :func:`main` (positional arguments cannot use default_map).
    """
    config_path = Path(value) if value else _DEFAULT_CONFIG
    if not config_path.exists():
        return value
    with open(config_path) as f:
        raw = yaml.safe_load(f) or {}
    normalized = {
        k.replace("-", "_"): v
        for k, v in raw.items()
        if k != "audio" and v is not None
    }
    ctx.default_map = normalized
    return str(config_path)


@click.command(context_settings={"help_option_names": ["-h", "--help"]})
@click.option(
    "--config",
    default=None,
    is_eager=True,
    callback=_apply_config,
    type=click.Path(dir_okay=False),
    help=f"YAML config file [default: {_DEFAULT_CONFIG.name} next to this script]",
)
@click.argument("audio", nargs=-1, required=False)
@click.option(
    "--output", "-o",
    default=None,
    type=click.Path(),
    help="Output directory for results and spectrograms [default: <script_dir>/results]",
)
@click.option(
    "--n-samples", "-n",
    default=50,
    show_default=True,
    help="Number of random 12-second segments to sample per audio file.",
)
@click.option(
    "--seed",
    default=42,
    show_default=True,
    help="Random seed for reproducible segment selection.",
)
def main(
    config: Optional[str],
    audio: Tuple[str, ...],
    output: Optional[str],
    n_samples: int,
    seed: int,
) -> None:
    """Compare sox binary vs sox_tensorflow spectrograms for AUDIO files.

    AUDIO may be one or more local file paths, directories, or S3 URIs.
    If omitted, the ``audio`` list from --config (or config.yaml) is used.
    All CLI flags override values from the config file.
    """
    # audio is a positional nargs=-1 argument, so it can't use default_map;
    # fall back to the 'audio' key in the config file instead.
    if not audio:
        cfg_path = Path(config) if config else _DEFAULT_CONFIG
        if cfg_path.exists():
            with open(cfg_path) as f:
                cfg = yaml.safe_load(f) or {}
            raw_audio = cfg.get("audio", [])
            if isinstance(raw_audio, str):
                raw_audio = [raw_audio]
            audio = tuple(str(a) for a in raw_audio)
        if not audio:
            raise click.ClickException(
                "No audio input. Pass file/directory paths as arguments or set "
                "'audio' in the config file."
            )

    random.seed(seed)

    # Resolve output dirs
    base_out = Path(output) if output else _SCRIPT_DIR
    results_dir = base_out / "results"
    spectrograms_dir = base_out / "spectrograms"
    results_dir.mkdir(parents=True, exist_ok=True)
    spectrograms_dir.mkdir(parents=True, exist_ok=True)

    # Resolve audio inputs (downloads S3 files to temp if needed)
    click.echo("Resolving audio inputs...")
    audio_files = resolve_audio_inputs(audio)
    click.echo(f"Found {len(audio_files)} audio file(s).")

    all_overall_stats: List[Dict] = []
    all_decile_stats: List[Dict] = []

    for audio_path in audio_files:
        click.echo(f"\nProcessing {audio_path.name}...")
        base_filename = audio_path.stem

        try:
            duration = get_audio_duration(audio_path)
        except Exception as exc:
            click.echo(f"  Could not read duration: {exc}", err=True)
            continue

        click.echo(f"  Duration: {duration:.1f}s — sampling {n_samples} segments")

        try:
            start_times = generate_random_segments(duration, n_samples=n_samples)
        except ValueError as exc:
            click.echo(f"  Skipping: {exc}", err=True)
            continue

        for i, start_time in enumerate(start_times):
            click.echo(f"  Segment {i + 1:3d}/{n_samples}: {start_time:.2f}s", nl=False)
            try:
                overall, decile = compare_segment(
                    audio_path, start_time, i + 1, base_filename, spectrograms_dir
                )
                all_overall_stats.append(overall)
                all_decile_stats.extend(decile)
                click.echo(f"  accuracy={overall['accuracy']:.2f}%")
            except Exception as exc:
                click.echo(f"  ERROR: {exc}", err=True)

    if not all_overall_stats:
        click.echo("No segments were processed successfully.", err=True)
        raise SystemExit(1)

    # Write CSVs
    overall_csv = results_dir / "overall_comparison.csv"
    with open(overall_csv, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(all_overall_stats[0].keys()))
        writer.writeheader()
        writer.writerows(all_overall_stats)

    percentile_csv = results_dir / "percentile_comparison.csv"
    with open(percentile_csv, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(all_decile_stats[0].keys()))
        writer.writeheader()
        writer.writerows(all_decile_stats)

    # Print terminal summary
    click.echo(f"\n{'=' * 50}")
    click.echo("Overall Results")
    click.echo(f"{'=' * 50}")
    click.echo(f"  Segments processed : {len(all_overall_stats)}")
    click.echo(f"  Exact pixel match  : {np.mean([s['accuracy'] for s in all_overall_stats]):.3f}%")
    click.echo(f"  Within ±1          : {np.mean([s['pct_within_1'] for s in all_overall_stats]):.3f}%")
    click.echo(f"  Within ±5          : {np.mean([s['pct_within_5'] for s in all_overall_stats]):.3f}%")
    click.echo(f"  Max pixel diff     : {int(np.max([s['max_diff'] for s in all_overall_stats]))}")
    click.echo(f"\nResults saved to {results_dir}")


if __name__ == "__main__":
    main()
